##
##  Rundown - Render Rundown Scripts for Teleprompting
##  Copyright (c) 2023-2024 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

MD012:
    maximum: 2

MD014: false

