##
##  Rundown - Render Rundown Scripts for Teleprompting
##  Copyright (c) 2023-2025 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

services:
    rundown:
        container_name: rundown
        image:          engelschall/rundown:latest
        init:           false
        restart:        always
        privileged:     false
        command:        [ "-v", "info", "-m", "web-ui", "-a", "0.0.0.0", "-p", "8080" ]
        ports:
            - 8080:8080

